---
# Ce fichier est exécuté dans le dossier sécurisé: /home/amyv4492/git_repositories/easyconnect_git/

deployment:
  tasks:
    # ----------------------------------------------------
    # CONFIGURATION DES CHEMINS
    # Le chemin du backend (eeasyconnect_backend)
    - export BACKEND_PATH=/home/amyv4492/git_repositories/easyconnect_git/eeasyconnect_backend/
    # Le chemin du frontend (easyconnect)
    - export FRONTEND_PATH=/home/amyv4492/git_repositories/easyconnect_git/easyconnect/
    # Le chemin public où tout sera visible (à l'intérieur de public_html)
    - export WEB_ROOT=/home/amyv4492/easykonect.smil-app.com/easykonect_prod/    
    # ----------------------------------------------------
    # 1. MAINTENANCE (Optionnel)
    # - /usr/local/bin/php $BACKEND_PATH/artisan down

    # 2. DEPLOIEMENT DU BACKEND LARAVEL
    # A. Installation des dépendances Composer
    # Assurez-vous que ce chemin pour composer est correct sur votre serveur
# Nouvelle Tentative : Utilisation du chemin cPanel standard
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --working-dir=$BACKEND_PATH     
    # B. Optimisation et Configuration Laravel
    # Créez le fichier .env si nécessaire (MANUELLE ou via un autre script)
    - /usr/local/bin/php $BACKEND_PATH/artisan key:generate --force
    - /usr/local/bin/php $BACKEND_PATH/artisan config:cache
    - /usr/local/bin/php $BACKEND_PATH/artisan route:cache
    - /usr/local/bin/php $BACKEND_PATH/artisan view:cache
    - /usr/local/bin/php $BACKEND_PATH/artisan migrate --force

    # C. Copie du Laravel Public (API)
    # Le dossier public de Laravel ira dans /public_html/api
    - /bin/mkdir -p $WEB_ROOT/api/
    - /bin/cp -R $BACKEND_PATH/public/* $WEB_ROOT/api/
    
    # ----------------------------------------------------
    # 3. DEPLOIEMENT DU FRONTEND FLUTTER
    # On suppose que le build web a été fait localement dans easyconnect/build/web
    # Le frontend sera à la racine de public_html
    - /bin/cp -R $FRONTEND_PATH/build/web/* $WEB_ROOT/

    # 4. FIN DE LA MAINTENANCE (Optionnel)
    # - /usr/local/bin/php $BACKEND_PATH/artisan up